server:
  port: 8080
  servlet:
    context-path: /
#    一定要有空格
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_film
    username: root
    password: 11
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    ##模板引擎配置，在开发模式下一般配置为false
  thymeleaf:
    cache: false
    
imageFilePath: G:/JavaWorkspace/SpringBootFilm/src/main/webapp/static/filmImage/
    